services:
  postgres-weather:
    image: postgres:latest
    container_name: postgres-weather
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data     
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 4

  migrator:
    build: .
    container_name: migrator
    environment:
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DRIVER: ${DB_DRIVER}
    depends_on:
      postgres-weather:
        condition: service_healthy
    entrypoint: ["./migrate.sh"]
  api-weather:
    build: .
    container_name: api-weather
    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DRIVER: ${DB_DRIVER}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      APP_MODE: api
    depends_on:
      migrator:
        condition: service_completed_successfully
    entrypoint: ["./run.sh"]

  cron-weather:
    build: .
    container_name: cron-weather
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DRIVER: ${DB_DRIVER}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      APP_MODE: cron
    depends_on:
      postgres-weather:
        condition: service_healthy
    entrypoint: ["./run.sh"]
  
volumes:
  postgres-data: